name: giji34
api-version: 1.15
version: @version@
main: com.github.giji34.t.Main
commands:
  tpl:
    uasge: giji34:tpl <X> <Y> <Z>
  tpb:
    usage: giji34:tpb <Name of Landmark>
  gm:
    usage: giji34:gm
  gfill:
  greplace:
  gundo:
  gregenerate:
  gtree:
    usage: gtree <幹の長さ>
  guide:
    usage: guide <Player> <Name of Landmark>
  follow:
    usage: follow <Player>
  create_portal:
    usage: create_portal <name> <destinationSserver> <returnX> <returnY> <returnZ>
  delete_portal:
    usage: delete_portal <name>
  fell_trees:
  /chunk:
    usage: //chunk
  uuid:
  connect:
  kusa:
