api-version: 1.13
commands:
  tpl:
    uasge: giji34:tpl <X> <Y> <Z>
  tpb:
    usage: giji34:tpb <Name of Landmark>
  gm:
    description: Toggle gamemode between creative/spectator
    usage: giji34:gm
  gfill:
  greplace:
  gundo:
  gregenerate:
